[tool.pytest.ini_options]
pythonpath = ["dj"]
DJANGO_SETTINGS_MODULE = "config.settings"
norecursedirs = [".venv", "venv", "templates", "remote", ".vscode", ".*", "tmp", ]
python_files = ["test_*.py", "*_test.py", "*_tests.py"]